# Generated by Django 5.0.1 on 2024-01-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_author_author_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(upload_to='blog_authors'),
        ),
    ]
