# Generated by Django 5.0.1 on 2024-01-11 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blogauthorsorderable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogauthorsorderable',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogauthorsorderable',
            name='page',
        ),
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
        migrations.DeleteModel(
            name='BlogAuthorsOrderable',
        ),
    ]
