# Generated by Django 5.0.1 on 2024-01-14 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_comment_downvote_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='Default content'),
        ),
    ]
