# Generated by Django 5.0.1 on 2024-01-14 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_qamodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QAModel',
        ),
    ]
