# Generated by Django 5.0.1 on 2024-01-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_qamodel'),
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QAModel',
            new_name='QAModelPage',
        ),
    ]
