# Generated by Django 5.0.1 on 2024-01-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_rename_qamodel_qamodelpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qamodelpage',
            name='answer',
            field=models.CharField(max_length=1055),
        ),
    ]
