# Generated by Django 5.0.1 on 2024-01-14 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0031_alter_comment_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
