# Generated by Django 5.0.1 on 2024-01-14 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_remove_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='answer',
            new_name='answer_coment',
        ),
    ]
