# Generated by Django 5.0.1 on 2024-01-14 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_remove_answer_question_answer_question_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='question_text',
            new_name='question',
        ),
    ]
