# Generated by Django 5.0.1 on 2024-01-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
